name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  release:
    types:
      - published

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      NUGET_SRC: github
      REGISTRY_URL: https://nuget.pkg.github.com/fkthat/index.json
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Setup NuGet
        run: >-
          dotnet nuget add source $REGISTRY_URL -n $NUGET_SRC
          -u fkthat -p $GITHUB_TOKEN --store-password-in-clear-text
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore
        run: dotnet restore Templates.sln
      - name: Build
        run: dotnet build Templates.sln --no-restore -c Release
      - name: Pack
        run: dotnet pack FkThat.Templates.csproj --no-build -c Release
      - name: Push
        if: github.event_name == 'release'
        run: dotnet nuget push **/*.nupkg -s $NUGET_SRC
