name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      NUGET_SRC: github
      REGISTRY_URL: https://nuget.pkg.github.com/fkthat/index.json
      REGISTRY_PAT: ${{secrets.REGISTRY_PAT}}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Setup NuGet
        run: >-
          dotnet nuget add source $REGISTRY_URL -n $NUGET_SRC
          -u fkthat -p $REGISTRY_PAT --store-password-in-clear-text
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Pack
        run: dotnet pack --no-build

#      - name: Push
#        if: >-
#          github.event_name == 'push' &&
#          github.ref_name == 'main'
#        run: dotnet nuget push **/*.nupkg -s $NUGET_SRC --skip-duplicate
